//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAUGuideBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAUGuideBookTable
    {
        public int ContentId { get; set; }
        public string Title { get; set; }
        public string ContentDescription { get; set; }
        public string ContentPicture { get; set; }
        public string ContentVideo { get; set; }
        public Nullable<bool> ContentApproval { get; set; }
        public Nullable<System.DateTime> ContentDate { get; set; }
    }
}
